# Gera imagem do banco de dados mysql e a sobe para o repositorio local do Gitlab
# Usa o gitlab-runner executor SHELL. Nao usa imagems Docker no pipeline

variables:
    MYSQL_DATABASE: ifmt_db
    #MYSQL_ROOT_PASSWORD: ifmt2   # definido com variavel interna
    DOCKER_NET: db
    MYSQL_CONTAINER_NAME: meu-mysql
    MYSQL_CLIENT_CONTAINER_NAME: meu-phpMyadmin
stages:
    - construcao

criacao-imagem:
    stage: construcao
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    script:
        # construcao da imagem
        - docker build -t $CI_REGISTRY/devops/db-mysql:v1 .
        - echo "Imagem  construida!!+++ ! "
        # entrega da imagem no repositorio Docker
        - echo "Acessando o repositorio!!!" 
        - docker login -u  $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - echo "Logged in!!!"
        - docker push $CI_REGISTRY/devops/db-mysql:v1 
        - echo "Imagem entregue no repositorio!!!"