apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: pod-django-app
  type: NodePort
  ports:
    - name: nginx
      protocol: TCP
      port: 8089
      targetPort: 8000
      nodePort: 30100
