# Cria uma aplicacao Django e faz o delivery da imagem docker para reposotorio local Gitlab

services:
  - name: docker:26.1.3-dind  
    alias: docker

stages:
    - build
    #- deploy

build-image:
    image: docker
    stage: build
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    script:
        - echo "Docker info"
        - docker info
        - echo "Trying to Log in!!!   ---- $MY_CI_REGISTRY - & ---$CI_REGISTRY"
        - docker login -u  $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - echo "Logged in!!!"
        - docker build -t $CI_REGISTRY/devops/django-app:v1 .
        - echo "Image built!!!"
        - docker push $CI_REGISTRY/devops/django-app:v1
        - echo "Imagem  construida!!+++! "


# Com o executor DOCKER
deploy_containers:
    image: docker
    stage: deploy
    variables:
        DOCKER_TLS_CERTDIR: "/certs"   
    script:
        - echo "Trying to Log in!!!   ---- $MY_CI_REGISTRY - & ---$CI_REGISTRY"
        - docker login -u  $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - echo "Logged in!!!"
        - docker rm -f django-container 
        #- docker run -td --name django-container  -v mysql-data:/var/lib/mysql  -p 9200:8000 $CI_REGISTRY/devops/django-app:v1 
        - docker run -td --name django-container  -p 9200:8000 $CI_REGISTRY/devops/django-app:v1 